apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-k8s-scheduler-config
  namespace: kube-system
data:
  custom-k8s-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - pluginConfig:
          - args:
              # Custom plugin arguments can go here (e.g., CPU threshold)
              cpuUtilizationThreshold: 0.7  # 70% CPU threshold
            name: CustomCPUUtilizationScorer  # Name of the custom plugin
        plugins:
          score:
            enabled:
              - name: CustomCPUUtilizationScorer
                weight: 1  # You can adjust the weight of this plugin
            disabled:
              - name: "*"  # Disable other score plugins
          multiPoint:
              enabled:
                - name: CustomCPUUtilizationScorer
                  weight: 1
        schedulerName: custom-k8s-scheduler
    leaderElection:
      leaderElect: true
      resourceNamespace: kube-system
      resourceName: custom-k8s-scheduler
    clientConnection:
      burst: 200
      qps: 100
