apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-k8s-scheduler-config
  namespace: kube-system
data:
  custom-k8s-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - pluginConfig:
        - args:
            scoringStrategy:
              resources:
              - name: intel.com/foo
                weight: 3
              - name: intel.com/bar
                weight: 3
              requestedToCapacityRatio:
                shape:
                - utilization: 0
                  score: 0
                - utilization: 100
                  score: 10
              type: RequestedToCapacityRatio
          name: NodeResourcesFit
        plugins:
          score:
              enabled:
                  - name: NodeResourcesFit
                    weight: 1
              disabled:
                  - name: "*"
          multiPoint:
              enabled:
                  - name: NodeResourcesFit
                    weight: 1
        schedulerName: custom-k8s-scheduler
    leaderElection:
      leaderElect: true
      resourceNamespace: kube-system
      resourceName: custom-k8s-scheduler
    clientConnection:
      burst: 200
      qps: 100